# Generated by Django 4.1.3 on 2023-05-13 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Comment Likes'),
        ),
    ]
